// <auto-generated />
using System;
using Group_APT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group_APT.Migrations
{
    [DbContext(typeof(ExaminationContext))]
    partial class ExaminationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Group_APT.Models.Examination", b =>
                {
                    b.Property<string>("Paper_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location_Id");

                    b.Property<int>("QuestionAmount");

                    b.Property<string>("SelectionType");

                    b.Property<DateTime>("Time");

                    b.HasKey("Paper_Id");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("Group_APT.Models.Lecturer", b =>
                {
                    b.Property<string>("LecturerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasKey("LecturerId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("Group_APT.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Id");

                    b.Property<string>("Name");

                    b.Property<string>("StudentImageLocation");

                    b.Property<string>("Surname");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Group_APT.Models.Unit", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Code");

                    b.ToTable("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
