// <auto-generated />
namespace Test2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Teaching2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Teaching2));
        
        string IMigrationMetadata.Id
        {
            get { return "201903100806110_Teaching2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
